import assert from "node:assert/strict";
import { test } from "node:test";

import { hashPassword, TIMING_DUMMY_HASH, verifyPassword } from "./password";

test("a hashed password verifies, a wrong one does not", async () => {
  const hash = await hashPassword("preview-only-4821");

  assert.equal(await verifyPassword("preview-only-4821", hash), true);
  assert.equal(await verifyPassword("preview-only-4822", hash), false);
  assert.equal(await verifyPassword("", hash), false);
});

test("hashes are salted, so the same password hashes differently each time", async () => {
  const a = await hashPassword("same-password");
  const b = await hashPassword("same-password");

  assert.notEqual(a, b);
  assert.equal(await verifyPassword("same-password", a), true);
  assert.equal(await verifyPassword("same-password", b), true);
});

/**
 * The migration's central bet: passwords set through Supabase keep working.
 * This is a real GoTrue-format `$2a$` hash of "correct-horse", generated by
 * bcrypt — if bcryptjs ever stopped reading that format, every user would be
 * locked out at cutover and this test is what catches it first.
 */
test("verifies a bcrypt $2a$ hash of the kind GoTrue stored", async () => {
  const goTrueStyleHash = "$2a$10$uuO63.BwEoewuokesg7wY.JRrUsgl/mXAy5JbnhemNkCTTg/9831S";

  assert.equal(await verifyPassword("correct-horse", goTrueStyleHash), true);
  assert.equal(await verifyPassword("wrong-horse", goTrueStyleHash), false);
});

test("the timing dummy hash matches nothing", async () => {
  assert.equal(await verifyPassword("", TIMING_DUMMY_HASH), false);
  assert.equal(await verifyPassword("password", TIMING_DUMMY_HASH), false);
});
